name: 'File Type Restriction'
description: 'GitHub Action to restrict specific file types'
branding:
  icon: 'file-text'  
  color: 'green'
inputs:
  files:
    description: 'Comma separated restricted file types.'
    required: true
  throw_error:
    description: 'Makes the Action fail on restricted files.'
    default: true
    required: false
  committed_files:
    description: 'List of updated files'
    required: true
outputs:
  files_exists:
    description: 'Whether the restricted file(s) exists.'
runs:
  using: 'node12'
  main: 'dist/index.js'
